### ISSUE TITLE
reincarnated pusher Process-67299 after sudden death

### ISSUE THREAD

**Issue by MiKatre** [django-q2/django-q2#142] opened 2023-11-22 14:28 UTC
Basically, the task remains in the task queue and the LOCK keeps getting delayed again and again:

![Screenshot 2023-11-22 at 15 19 02](https://github.com/django-q2/django-q2/assets/19536324/c3ee8f5b-9bc8-409a-a610-217577057e21)

![Screenshot 2023-11-22 at 15 24 38](https://github.com/django-q2/django-q2/assets/19536324/72fed049-f25d-49b5-9957-37517efe221b)

![Screenshot 2023-11-22 at 15 31 06](https://github.com/django-q2/django-q2/assets/19536324/043c4bdb-b52a-4a8d-8a63-7fbdc74f426b)

Each time it is delayed, an error is logged by Sentry:
`reincarnated pusher Process-67299 after sudden death`

![Screenshot 2023-11-22 at 15 17 57](https://github.com/django-q2/django-q2/assets/19536324/707d4ad2-b9be-41e0-bef5-0019821e0294)

This error keeps happening again and again. It can last minutes or hours until eventually, it succeeds.

The server is not under provisioned.

Settings:
```Python
Q_CLUSTER = {
    "name": "DjangORM",
    "workers": 1,
    "timeout": 600,
    "retry": 660,
    "max_attempts": 2,
    "queue_limit": 5,
    "orm": "default",
    "save_limit": 100,
    "cpu_affinity": 1,
    "poll": 30,  # seconds
    "label": "Django Q",
}
```

Nothing in server logs:
```Sh
logs www -p worker
2023-11-22T13:56:30.747987702Z app[worker.1]: 13:56:30 [Q] INFO Q Cluster kitten-football-ink-lemon starting.
2023-11-22T13:56:31.026708338Z app[worker.1]: 13:56:31 [Q] INFO Process-d66426f9a9414e79b470d6626c32da5f ready for work at 10
2023-11-22T13:56:31.034705233Z app[worker.1]: 13:56:31 [Q] INFO Process-6bb0de4ad63247159102f7b7db2c3758 monitoring at 11
2023-11-22T13:56:31.042050692Z app[worker.1]: 13:56:31 [Q] INFO Process-d8cabe8895fd4d1c90a2e6fc465639c3 guarding cluster kitten-football-ink-lemon [DjangORM]
2023-11-22T13:56:31.044854231Z app[worker.1]: 13:56:31 [Q] INFO Process-a6c383413b6548e5ab94de0e525f6681 pushing tasks at 12
2023-11-22T13:56:31.060123817Z app[worker.1]: 13:56:31 [Q] INFO Q Cluster kitten-football-ink-lemon [DjangORM] running.
```

**Comment by MiKatre** [comment] 2023-11-22 18:27
After 5 hours, it finally succeeded:

![Screenshot 2023-11-22 at 19 24 45](https://github.com/django-q2/django-q2/assets/19536324/3cc18bb1-0002-49e3-b060-37a36edbe2a1)

```
Started: Nov. 22, 2023, 12:59 p.m.
Stopped: Nov. 22, 2023, 6 p.m.
Attempt count: 1
```

**Comment by GDay** [comment] 2023-11-24 03:01
What kind of database are you using? Postgres, MySQL....? And what is the connection timeout value?

It sounds like the scheduler isn't able to pull tasks from the broker (in your case the Django database). 

Right now, the only thing that stands out is the `poll` value. It might be too high, which times out the database connection and therefore let's the pusher crash.

**Comment by GDay** [comment] 2023-11-24 12:56
Hmm... interesting. Yeah, likely not related to the poll value.

What kind of arguments are you sending with that function?

**Comment by MiKatre** [comment] 2023-11-24 17:08
I am using `async_task` on `BaseMailer.send_email` which accepts basically the same arguments as Django's `send_mail`, with the addition of headers.


Here is the relevant code:
```Python
def deliver_later(self):
    async_task(
        BaseMailer.send_email,
        self.user,
        self.subject,
        self.txt_content,
        self.html_content,
        self.headers,
        self.from_email,
    )
```


```Python
# BaseMailer.send_email
@staticmethod
def send_email(
    user,
    subject,
    txt_content,
    html_content=None,
    from_email=settings.DEFAULT_FROM_EMAIL,
    headers=None,
):
    if headers is None:
        headers = BaseMailer.HEADERS.copy()

    to = user.email

    email = EmailMultiAlternatives(
        subject, txt_content, from_email, [to], headers=headers
    )
    if html_content is not None:
        email.attach_alternative(html_content, "text/html")

    email.send()
```

Args:
```Python
# headers
headers = {
        "X-Mailgun-Track": "yes",
        "X-Mailgun-Track-Clicks": "yes",
        "X-Mailgun-Track-Opens": "yes",
}

# txt_content
txt_content = render_to_string(
    template_name_txt,
    {
        "website": website,
        "site": Site.objects.get_current(),
    },
)

# html_content
html_content = render_to_string(
    template_name_html,
    {
        "website": website,
        "site": Site.objects.get_current(),
    },
)

```

**Comment by MiKatre** [comment] 2023-11-25 00:04
Example of stuck task with actual arguments:

![Screenshot 2023-11-25 at 00 55 59](https://github.com/django-q2/django-q2/assets/19536324/baf33bd7-9b55-4598-836d-6725cd10feec)

**Comment by GDay** [comment] 2023-11-25 00:06
Thanks a lot for all the info. I will try to reproduce this issue on my pc tomorrow.

**Comment by MiKatre** [comment] 2023-11-25 00:37
Thanks! 
Another data point: I just ran my email function in a loop to send myself 5 *identical* welcome emails. 4 went through right away, 1 is stuck.

**Comment by GDay** [comment] 2023-11-26 01:17
Thanks. This is really strange. I haven't been able to reproduce this issue at all. Even with very similar functions as you (running 10 tasks at once). 

You mentioned:

> Nothing in server logs:

What you posted was the first bit of the logs. There should be a lot more. Could you check the last part instead?

I am still not sure why the pusher is getting killed with this specific task. I have never had this issue with any of my projects.

I suspect that the database is the cause of why the process is getting killed (based on the logs you provided). This SO post seems related: https://stackoverflow.com/a/26129952/3287377.

They state there that a lot of data was the cause for their crashes. I am suspecting that pushing the entire email (`html_content`) is too much to handle for the database and it then kills the connection. Django-q2 serializes and signs the data before it gets put in the broker (in your case the postgres database), which could become a very long string.

My suggestion would be to change the function to pass the template name to the async task and then get the full text when django-q is running the task and see if that solves the issue for you.

Why this doesn't happen all the time, but only fairly random is still a mystery to me. Maybe the database is under heavier load at those times and this task might be the tipping point?

**Comment by MiKatre** [comment] 2023-12-02 17:45
Sorry of the late response. Thanks for looking into it ! And with so little information to work from. I tried to do a minimal reproduction with my functions but could not reproduce the error either. It just works.

The database load curves seemed completely uncorrelated with the bug.

In the end, double checking my Django/Postgres configuration, I uninstalled `psycopg2` and installed the newer and recommended `psycopg` adapter  instead. That seems to have solved the problem !

Two hours error free despite trying to get it to err by bulking async emails, so touching wood right now.

**Comment by GDay** [comment] 2023-12-03 00:30
Thanks for reporting back. Great to hear that updating pycopg has seemed to solve it. I will close the issue, if you get the issue again, then feel free to reopen!

**Closed by GDay** 2023-12-03 00:30 UTC

**Comment by MiKatre** [comment] 2023-12-21 10:47
Hey, here is an update in the issue.

Updating `psycopg` solution didn't work at all in the end.

Now I use Redis as Broker and it got better.

Before/After Redis:
![Screenshot 2023-12-21 at 10 17 18](https://github.com/django-q2/django-q2/assets/19536324/6f94ae8b-c3e4-4047-ba8f-dff76af603ae)

Now pusher still gets occasionally reincarnated. But it is not the case anymore that a task get stuck for hours because the process keeps being reincarnated.

Maybe it is a RAM constraint according to https://github.com/Koed00/django-q/issues/711, but for now it works well enough for my use case.
