### ISSUE TITLE
django_q.Task: (models.W037) MySQL does not support indexes with conditions.

### ISSUE THREAD

**Issue by afroginawell** [django-q2/django-q2#245] opened 2024-10-30 18:10 UTC
When I switched from `django-q==1.3.9` to `django-q2==1.7.3`, the following warning message appeared while executing `python manage.py migrate`:
```
System check identified some issues:

WARNINGS:
django_q.Task: (models.W037) MySQL does not support indexes with conditions.
	HINT: Conditions will be ignored. Silence this warning if you don't care about it.
```
I want to know if this warning will have a negative impact on my service?

mysqlclient==2.2.4
Django==4.2.16
Python: 3.9.10

**Comment by GDay** [comment] 2024-10-30 20:48
Duplicate of https://github.com/django-q2/django-q2/issues/242

No, it doesn't matter. Only if you have millions of failing tasks saved, you will notice a slight difference in speed. See here: https://github.com/django-q2/django-q2/issues/160

**Closed by GDay** 2024-10-30 20:48 UTC
