### ISSUE TITLE
In the new version 1.5.5, there was an error running: Apps aren't loaded yet

### ISSUE THREAD

**Issue by dongfangtianyu** [django-q2/django-q2#109] opened 2023-09-05 08:45 UTC
The following error occurred after upgrading version 1.5.5 (rolling back to 1.5.4 to restore normal)：

```
PS C:\Users\123\PycharmProjects\Tesla> pdm run .\manage.py qcluster
15:58:07 [Q] INFO Q Cluster colorado-tennis-bravo-equal starting.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\123\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\123\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\123\Tesla\lib\site-packages\django_q\cluster.py", line 12, in <module>
    from django_q.monitor import monitor
  File "C:\Users\123\Tesla\lib\site-packages\django_q\monitor.py", line 7, in <module>
    import django_q.tasks
  File "C:\Users\123\Tesla\lib\site-packages\django_q\tasks.py", line 14, in <module>
    from django_q.models import Schedule, Task
  File "C:\Users\123\Tesla\lib\site-packages\django_q\models.py", line 28, in <module>
    class Task(models.Model):
  File "C:\Users\123\Tesla\lib\site-packages\django\db\models\base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\123\Tesla\lib\site-packages\django\apps\registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\123\Tesla\lib\site-packages\django\apps\registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

```

environment:
```
OS: Windows 10
Python: 3.10
Django_q2: 1.5.5
```

particulars:
```
null   （Before further analysis, report to the community first）
```

**Comment by GDay** [comment] 2023-09-05 12:18
Thanks for the report!

This is very strange, I haven't been able to reproduce it either:

```
root@cc927ea9e6b6:/app# pip freeze | grep "django-q2" 
django-q2==1.5.5 
root@cc927ea9e6b6:/app# python manage.py qcluster
INFO Q Cluster nitrogen-diet-happy-mango starting.
INFO Process-c4b06452e38c4723a3e7a68b5487d49f ready for work at 14
INFO Process-86fa4e254c62445ba48ee29f79ff00db monitoring at 15
INFO Process-4a0174801f4c430abc35313a4a465bbb guarding cluster nitrogen-diet-happy-mango [DjangORM]
INFO Process-c37e502e0e974fb4a6f2e027cd880bd8 pushing tasks at 16
INFO Q Cluster nitrogen-diet-happy-mango [DjangORM] running.
```

**Comment by zN3utr4l** [comment] 2023-09-06 08:21
**Same error occurred**

```
(django-q2-example) (django-q2-example) PS D:\Repository\Analysis Detection\ReplaceCelery\django_q2_example> python manage.py qcluster
D:\Users\my\micromamba\envs\django-q2-example\lib\site-packages\django_q\conf.py:174: UserWarning: Retry and timeout are misconfigured. Set retry larger than timeout,failure to do so will cause the tasks to be retriggered before completion.See https://django-q2.readthedocs.io/en/master/configure.html#retry for details.
  warn(
10:16:16 [Q] INFO Q Cluster jupiter-moon-beer-single starting.
D:\Users\my\micromamba\envs\django-q2-example\lib\site-packages\django_q\conf.py:174: UserWarning: Retry and timeout are misconfigured. Set retry larger than timeout,failure to do so will cause the tasks to be retriggered before completion.See https://django-q2.readthedocs.io/en/master/configure.html#retry for details.
  warn(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Users\my\micromamba\envs\django-q2-example\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Users\my\micromamba\envs\django-q2-example\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\Users\my\micromamba\envs\django-q2-example\lib\site-packages\django_q\cluster.py", line 12, in <module>
    from django_q.monitor import monitor
  File "D:\Users\my\micromamba\envs\django-q2-example\lib\site-packages\django_q\monitor.py", line 7, in <module>
    import django_q.tasks
  File "D:\Users\my\micromamba\envs\django-q2-example\lib\site-packages\django_q\tasks.py", line 14, in <module>
    from django_q.models import Schedule, Task
  File "D:\Users\my\micromamba\envs\django-q2-example\lib\site-packages\django_q\models.py", line 28, in <module>
    class Task(models.Model):
  File "D:\Users\my\micromamba\envs\django-q2-example\lib\site-packages\django\db\models\base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "D:\Users\my\micromamba\envs\django-q2-example\lib\site-packages\django\apps\registry.py", line 253, in get_containing_app_config
    self.check_apps_ready()
  File "D:\Users\my\micromamba\envs\django-q2-example\lib\site-packages\django\apps\registry.py", line 136, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by GDay** [comment] 2023-09-06 08:42
@zN3utr4l Looks like you are on Windows as well? 
Might be an issue specific to Windows then... hmm.. I will take a look later.

**Comment by GDay** [comment] 2023-09-06 10:16
@zN3utr4l regarding the ctrl+c issue, you might want to take a look at this: https://github.com/django-q2/django-q2/issues/66
Windows handles that differently, you might need a different key combo for that. You need the `Ctrl + Break` combo (and the actual key combo can differ per computer)

**Comment by diefenbach** [comment] 2023-09-08 08:31
Same is true for macOS Ventura 13.4 (22F66):

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kaidiefenbach/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/kaidiefenbach/.pyenv/versions/3.10.2/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/kaidiefenbach/.pyenv/versions/asign-migrator/lib/python3.10/site-packages/django_q/cluster.py", line 12, in <module>
    from django_q.monitor import monitor
  File "/Users/kaidiefenbach/.pyenv/versions/asign-migrator/lib/python3.10/site-packages/django_q/monitor.py", line 7, in <module>
    import django_q.tasks
  File "/Users/kaidiefenbach/.pyenv/versions/asign-migrator/lib/python3.10/site-packages/django_q/tasks.py", line 14, in <module>
    from django_q.models import Schedule, Task
  File "/Users/kaidiefenbach/.pyenv/versions/asign-migrator/lib/python3.10/site-packages/django_q/models.py", line 28, in <module>
    class Task(models.Model):
  File "/Users/kaidiefenbach/.pyenv/versions/asign-migrator/lib/python3.10/site-packages/django/db/models/base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/kaidiefenbach/.pyenv/versions/asign-migrator/lib/python3.10/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/kaidiefenbach/.pyenv/versions/asign-migrator/lib/python3.10/site-packages/django/apps/registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`

**Comment by ethrgeist** [comment] 2023-09-11 09:26
Can confirm, 1.5.4 works fine, 1.5.5 has the app not loaded issue.

Python 3.9.13, Windows 11.

**Comment by rasulkireev** [comment] 2023-09-12 17:02
Have the same issue on MacOS Ventura 13.5, Python 3.11.4, q2 1.5.5.

**Comment by GDay** [comment] 2023-09-12 20:45
Sorry, I am all caught up with work at the moment. I will try to fix this on Thursday. I still haven't been able to reproduce this (on Linux), but will try on a windows machine then.

Thanks for all the reports. It's great to see that this package is getting used in quite a few projects!

**Comment by diefenbach** [comment] 2023-09-13 12:46
Thanks for you effort. This package is really great!

**Comment by ethrgeist** [comment] 2023-09-14 09:07
Tried another project of mine, same issue.

Windows 11, Python 3.11, tested Django 4.2.4 and Django 4.2.5., both yield this error after `manage.py qcluster`, version 1.5.4. works fine.

```
2023-09-14 11:03:05,136 DEBUG __init__: couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
2023-09-14 11:03:05,543 INFO cluster: Q Cluster mexico-juliet-echo-zebra starting.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python311\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\spawn.py", line 132, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\funny-django\Lib\site-packages\django_q\cluster.py", line 12, in <module>
    from django_q.monitor import monitor
  File "C:\Users\user\.virtualenvs\funny-django\Lib\site-packages\django_q\monitor.py", line 7, in <module>
    import django_q.tasks
  File "C:\Users\user\.virtualenvs\funny-django\Lib\site-packages\django_q\tasks.py", line 14, in <module>
    from django_q.models import Schedule, Task
  File "C:\Users\user\.virtualenvs\funny-django\Lib\site-packages\django_q\models.py", line 28, in <module>
    class Task(models.Model):
  File "C:\Users\user\.virtualenvs\funny-django\Lib\site-packages\django\db\models\base.py", line 129, in __new__
    app_config = apps.get_containing_app_config(module)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.virtualenvs\funny-django\Lib\site-packages\django\apps\registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\user\.virtualenvs\funny-django\Lib\site-packages\django\apps\registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by GDay** [comment] 2023-09-15 01:15
Thanks.

I think the main issue here is that the imports got sorted differently (some Django_q2 parts get imported earlier than the check if django is ready). I have now changed the order of the import and removed/changed a few in this PR: https://github.com/django-q2/django-q2/pull/116.

Still need to test it, but I am fairly certain that that will fix the issue.

**Comment by alexerhardt** [comment] 2023-10-06 16:02
FYI, same issue on macOS 12.0.1, Python 3.10.13

Also fixed reverting to 1.5.4

Thanks for your great work!

**Comment by GDay** [comment] 2023-10-07 00:23
Thanks. Yeah, I have reproduced the issue on a windows machine. Linux (containers) don't seem to have an issue with it, which is interesting. Haven't had much time yet to get to the bottom of it. I will have some time this weekend to take another look.

**Comment by GDay** [comment] 2023-10-08 16:18
I found the issue and the solution is in the PR I created. Confirmed it working on my windows machine. I still need to merge it and then create a new release for it. Will do that in the next few days, don't have time for that today anymore.

The issue was that all processes start with a different file and those files have not initialized django yet. The solution was to setup django in the scheduler, worker, monitor and pusher all separately. I don't know why it worked on linux, but that's not important anymore.

**Comment by GDay** [comment] 2023-10-13 00:15
@dongfangtianyu  @rasulkireev  @ethrgeist @alexerhardt @diefenbach v1.6.0 has been released which includes a fix for this (as well as other cool updates; support for Python 12 and Django 5!). It should be working fine on windows/mac now. Let me know if you are still having issue!

**Closed by GDay** 2023-10-13 00:15 UTC
